=== fran-bl/nba-teams-dataset/schema.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "http://example.com/schema.json",
    "type": "array",
    "default": [],
    "title": "NBA Teams",
    "description": "Schema za prikaz podataka o NBA timovima, uključujući osnovne informacije, postignuća i vlasnike.",
    "items": {
        "type": "object",
        "title": "nba_team",
        "description": "Objekt koji sadrži sve podatke o jednom NBA timu.",
        "required": [
            "team_id",
            "team_name",
            "abbreviation",
            "location",
            "arena_name",
            "established_year",
            "championships_won",
            "conference_titles",
            "division_titles",
            "all_time_wins",
            "all_time_win_percentage",
            "mascot",
            "head_coach",
            "owners"
        ],
        "properties": {
            "team_id": {
                "type": "integer",
                "title": "Jedinstveni identifikator tima",
                "description": "Jedinstveni identifikator za svaki tim"
            },
            "team_name": {
                "type": "string",
                "title": "Ime tima",
                "description": "Puni naziv NBA tima"
            },
            "abbreviation": {
                "type": "string",
                "title": "Skraćenica",
                "description": "Skraćeni naziv tima (npr. BOS za Boston Celtics)"
            },
            "location": {
                "type": "string",
                "title": "Lokacija tima",
                "description": "Grad ili mjesto gdje tim igra"
            },
            "arena_name": {
                "type": "string",
                "title": "Naziv arene",
                "description": "Naziv arene u kojoj tim igra domaće utakmice"
            },
            "established_year": {
                "type": "integer",
                "title": "Godina osnivanja",
                "description": "Godina kada je tim osnovan"
            },
            "championships_won": {
                "type": "integer",
                "title": "Osvojeni naslovi",
                "description": "Ukupan broj osvojenih NBA prvenstava"
            },
            "conference_titles": {
                "type": "integer",
                "title": "Konferencijski naslovi",
                "description": "Ukupan broj osvojenih naslova u konferenciji"
            },
            "division_titles": {
                "type": "integer",
                "title": "Divizijski naslovi",
                "description": "Ukupan broj osvojenih divizijskih naslova"
            },
            "all_time_wins": {
                "type": "integer",
                "title": "Ukupne pobjede",
                "description": "Ukupan broj pobjeda tima kroz povijest"
            },
            "all_time_win_percentage": {
                "type": "number",
                "title": "Postotak pobjeda",
                "description": "Postotak pobjeda tima kroz povijest"
            },
            "mascot": {
                "type": [
                    "string",
                    "null"
                ],
                "title": "Maskota",
                "description": "Ime maskote tima, ako postoji"
            },
            "head_coach": {
                "type": "string",
                "title": "Trener",
                "description": "Ime trenutnog trenera tima"
            },
            "owners": {
                "type": "array",
                "title": "Vlasnici",
                "description": "Lista vlasnika tima",
                "items": {
                    "type": "object",
                    "title": "Vlasnik",
                    "required": [
                        "owner_id",
                        "owner_name"
                    ],
                    "properties": {
                        "owner_id": {
                            "type": "integer",
                            "title": "Jedinstveni identifikator vlasnika",
                            "description": "Jedinstveni identifikator svakog vlasnika"
                        },
                        "owner_name": {
                            "type": "string",
                            "title": "Ime vlasnika",
                            "description": "Ime i prezime vlasnika"
                        }
                    }
                }
            }
        }
    }
}

=== fran-bl/nba-teams-dataset/nba-teams.json
[
    {
        "team_id": 0,
        "team_name": "Atlanta Hawks",
        "abbreviation": "ATL",
        "location": "Atlanta",
        "arena_name": "State Farm Arena",
        "established_year": 1949,
        "championships_won": 1,
        "conference_titles": 0,
        "division_titles": 12,
        "all_time_wins": 2929,
        "all_time_win_percentage": 0.493,
        "mascot": "Harry the Hawk",
        "head_coach": "Quin Snyder",
        "owners": [
            {
                "owner_id": 0,
                "owner_name": "Tony Ressler"
            }
        ]
    },
    {
        "team_id": 1,
        "team_name": "Boston Celtics",
        "abbreviation": "BOS",
        "location": "Boston",
        "arena_name": "TD Garden",
        "established_year": 1946,
        "championships_won": 18,
        "conference_titles": 11,
        "division_titles": 34,
        "all_time_wins": 3636,
        "all_time_win_percentage": 0.595,
        "mascot": "Lucky the Leprechaun",
        "head_coach": "Joe Mazzulla",
        "owners": [
            {
                "owner_id": 1,
                "owner_name": "Wyc Grousbeck"
            }
        ]
    },
    {
        "team_id": 2,
        "team_name": "Brooklyn Nets",
        "abbreviation": "BKN",
        "location": "Brooklyn",
        "arena_name": "Barclays Center",
        "established_year": 1976,
        "championships_won": 2,
        "conference_titles": 2,
        "division_titles": 5,
        "all_time_wins": 2028,
        "all_time_win_percentage": 0.440,
        "mascot": null,
        "head_coach": "Jordi Fernandez",
        "owners": [
            {
                "owner_id": 2,
                "owner_name": "Joe Tsai"
            }
        ]
    },
    {
        "team_id": 3,
        "team_name": "Charlotte Hornets",
        "abbreviation": "CHA",
        "location": "Charlotte",
        "arena_name": "Spectrum Center",
        "established_year": 1988,
        "championships_won": 0,
        "conference_titles": 0,
        "division_titles": 0,
        "all_time_wins": 1175,
        "all_time_win_percentage": 0.433,
        "mascot": "Hugo the Hornet",
        "head_coach": "Charles Lee",
        "owners": [
            {
                "owner_id": 3,
                "owner_name": "Rick Schnall"
            }
        ]
    },
    {
        "team_id": 4,
        "team_name": "Chicago Bulls",
        "abbreviation": "CHI",
        "location": "Chicago",
        "arena_name": "United Center",
        "established_year": 1966,
        "championships_won": 6,
        "conference_titles": 6,
        "division_titles": 9,
        "all_time_wins": 2384,
        "all_time_win_percentage": 0.509,
        "mascot": "Benny the Bull",
        "head_coach": "Billy Donovan",
        "owners": [
            {
                "owner_id": 4,
                "owner_name": "Michael Reinsdorf"
            }
        ]
    },
    {
        "team_id": 5,
        "team_name": "Cleveland Cavaliers",
        "abbreviation": "CLE",
        "location": "Cleveland",
        "arena_name": "Rocket Mortgage FieldHouse",
        "established_year": 1970,
        "championships_won": 1,
        "conference_titles": 5,
        "division_titles": 7,
        "all_time_wins": 2034,
        "all_time_win_percentage": 0.467,
        "mascot": "Moondog",
        "head_coach": "Kenny Atkinson",
        "owners": [
            {
                "owner_id": 5,
                "owner_name": "Dan Gilbert"
            }
        ]
    },
    {
        "team_id": 6,
        "team_name": "Dallas Mavericks",
        "abbreviation": "DAL",
        "location": "Dallas",
        "arena_name": "American Airlines Center",
        "established_year": 1980,
        "championships_won": 1,
        "conference_titles": 3,
        "division_titles": 5,
        "all_time_wins": 1798,
        "all_time_win_percentage": 0.507,
        "mascot": "Champ",
        "head_coach": "Jason Kidd",
        "owners": [
            {
                "owner_id": 6,
                "owner_name": "Patrick Dumont"
            }
        ]
    },
    {
        "team_id": 7,
        "team_name": "Denver Nuggets",
        "abbreviation": "DEN",
        "location": "Denver",
        "arena_name": "Ball Arena",
        "established_year": 1976,
        "championships_won": 1,
        "conference_titles": 1,
        "division_titles": 13,
        "all_time_wins": 2367,
        "all_time_win_percentage": 0.513,
        "mascot": "Rocky the Mountain Lion",
        "head_coach": "Michael Malone",
        "owners": [
            {
                "owner_id": 7,
                "owner_name": "Stan Kroenke"
            }
        ]
    },
    {
        "team_id": 8,
        "team_name": "Detroit Pistons",
        "abbreviation": "DET",
        "location": "Detroit",
        "arena_name": "Little Caesars Arena",
        "established_year": 1948,
        "championships_won": 3,
        "conference_titles": 5,
        "division_titles": 11,
        "all_time_wins": 2827,
        "all_time_win_percentage": 0.471,
        "mascot": "Hooper",
        "head_coach": "J.B. Bickerstaff",
        "owners": [
            {
                "owner_id": 8,
                "owner_name": "Tom Gores"
            }
        ]
    },
    {
        "team_id": 9,
        "team_name": "Golden State Warriors",
        "abbreviation": "GSW",
        "location": "San Francisco",
        "arena_name": "Chase Center",
        "established_year": 1946,
        "championships_won": 7,
        "conference_titles": 7,
        "division_titles": 12,
        "all_time_wins": 2971,
        "all_time_win_percentage": 0.487,
        "mascot": null,
        "head_coach": "Steve Kerr",
        "owners": [
            {
                "owner_id": 9,
                "owner_name": "Joe Lacob"
            }
        ]
    },
    {
        "team_id": 10,
        "team_name": "Houston Rockets",
        "abbreviation": "HOU",
        "location": "Houston",
        "arena_name": "Toyota Center",
        "established_year": 1967,
        "championships_won": 2,
        "conference_titles": 4,
        "division_titles": 8,
        "all_time_wins": 2370,
        "all_time_win_percentage": 0.514,
        "mascot": "Clutch the Bear",
        "head_coach": "Ime Udoka",
        "owners": [
            {
                "owner_id": 10,
                "owner_name": "Tilman Fertitta"
            }
        ]
    },
    {
        "team_id": 11,
        "team_name": "Indiana Pacers",
        "abbreviation": "IND",
        "location": "Indianapolis",
        "arena_name": "Gainbridge Fieldhouse",
        "established_year": 1976,
        "championships_won": 3,
        "conference_titles": 1,
        "division_titles": 9,
        "all_time_wins": 2358,
        "all_time_win_percentage": 0.511,
        "mascot": "Boomer",
        "head_coach": "Rick Carlisle",
        "owners": [
            {
                "owner_id": 11,
                "owner_name": "Herb Simon"
            }
        ]
    },
    {
        "team_id": 12,
        "team_name": "Los Angeles Clippers",
        "abbreviation": "LAC",
        "location": "Los Angeles",
        "arena_name": "Intuit Dome",
        "established_year": 1970,
        "championships_won": 0,
        "conference_titles": 0,
        "division_titles": 3,
        "all_time_wins": 1843,
        "all_time_win_percentage": 0.423,
        "mascot": "Chuck the Condor",
        "head_coach": "Tyronn Lue",
        "owners": [
            {
                "owner_id": 12,
                "owner_name": "Steve Ballmer"
            }
        ]
    },
    {
        "team_id": 13,
        "team_name": "Los Angeles Lakers",
        "abbreviation": "LAL",
        "location": "Los Angeles",
        "arena_name": "Crypto.com Arena",
        "established_year": 1948,
        "championships_won": 17,
        "conference_titles": 19,
        "division_titles": 33,
        "all_time_wins": 3552,
        "all_time_win_percentage": 0.591,
        "mascot": null,
        "head_coach": "JJ Redick",
        "owners": [
            {
                "owner_id": 13,
                "owner_name": "Jeanie Buss"
            }
        ]
    },
    {
        "team_id": 14,
        "team_name": "Memphis Grizzlies",
        "abbreviation": "MEM",
        "location": "Memphis",
        "arena_name": "FedExForum",
        "established_year": 1995,
        "championships_won": 0,
        "conference_titles": 0,
        "division_titles": 2,
        "all_time_wins": 999,
        "all_time_win_percentage": 0.432,
        "mascot": "Grizz",
        "head_coach": "Taylor Jenkins",
        "owners": [
            {
                "owner_id": 14,
                "owner_name": "Robert Pera"
            }
        ]
    },
    {
        "team_id": 15,
        "team_name": "Miami Heat",
        "abbreviation": "MIA",
        "location": "Miami",
        "arena_name": "Kaseya Center",
        "established_year": 1988,
        "championships_won": 3,
        "conference_titles": 7,
        "division_titles": 16,
        "all_time_wins": 1521,
        "all_time_win_percentage": 0.527,
        "mascot": "Burnie",
        "head_coach": "Erik Spoelstra",
        "owners": [
            {
                "owner_id": 15,
                "owner_name": "Micky Arison"
            }
        ]
    },
    {
        "team_id": 16,
        "team_name": "Milwaukee Bucks",
        "abbreviation": "MIL",
        "location": "Milwaukee",
        "arena_name": "Fiserv Forum",
        "established_year": 1968,
        "championships_won": 2,
        "conference_titles": 3,
        "division_titles": 19,
        "all_time_wins": 2390,
        "all_time_win_percentage": 0.528,
        "mascot": "Bango",
        "head_coach": "Doc Rivers",
        "owners": [
            {
                "owner_id": 16,
                "owner_name": "Wesley Edens"
            }
        ]
    },
    {
        "team_id": 17,
